// Example sentences, generated once and stored here on 2026-08-27.
// Static on purpose: a sentence for a word never changes, so there is no
// reason to ask for it again at runtime. Words added to the sheet later fall
// back to the sheet's own example until this file is regenerated.
var SENTENCES = {
"acquaint-1": "Our teacher spent Monday helping us acquaint ourselves with the new library computers.",
"adequate-1": "One water bottle each was adequate for our short hike, so we left the rest home.",
"adhere-1": "Swimmers must adhere to the pool rules, so nobody runs or dives in the shallow end.",
"adhere-2": "Wet leaves adhere to my boots so tightly that I have to scrape them off.",
"adversary-1": "My chess adversary smiled across the board and moved her queen to trap my king.",
"affinity-1": "My sister has a natural affinity for animals, and even shy cats come to her.",
"allegation-1": "The allegation that Mia copied her homework faded once nobody could show any real proof.",
"alluring-1": "The smell of warm cookies was so alluring that I followed it straight to the kitchen.",
"aloof-1": "The new boy stayed aloof at recess, watching our games from a bench without speaking.",
"appease-1": "Dad appeased my crying little sister by handing her the toy she had been begging for.",
"apprehensive-1": "I felt apprehensive before the spelling bee, sure I would forget every word on stage.",
"apt-1": "\"Muddy Monster\" was an apt nickname for my dog after his run through the swamp.",
"apt-2": "Such an apt learner, she understood the new card game after watching just one round.",
"aptitude-1": "Wesley has a real aptitude for drawing horses, even though nobody ever taught him how.",
"arduous-1": "Shoveling the whole driveway after the storm was arduous work, and my arms ached for hours.",
"assiduous-1": "My assiduous brother practises piano an hour every day, even on holidays and weekends.",
"assortment-1": "Grandpa's tin held an assortment of buttons, each a different colour, shape, and size.",
"asunder-1": "The wind ripped our old kite asunder, scattering paper and sticks across the field.",
"audacity-1": "My little brother had the audacity to call Grandma's cooking gross right at the dinner table.",
"audacity-2": "With great audacity, she dived from the highest board while the whole swim team watched.",
"barren-1": "Nothing grew on the barren hillside, just dry dust, cracked ground, and a few stones.",
"bemoan-1": "My brother began to bemoan the rain that washed out his birthday baseball game.",
"brusque-1": "The bus driver's brusque \"Sit down!\" made us all go quiet and stop laughing.",
"catastrophe-1": "The earthquake was a catastrophe that flattened houses and left many families with nothing.",
"confer-1": "Let us confer with the rest of the team before we choose a captain.",
"contempt-1": "The cat stared at her cheap new food with total contempt and walked away.",
"contradict-1": "My little brother loves to contradict me, saying black whenever I say white.",
"controversy-1": "The referee's final whistle caused a huge controversy, with parents shouting at each other for days.",
"cryptic-1": "My sister sent a cryptic text saying only \"the box knows\", and I still cannot understand it.",
"deduce-1": "From the crumbs on his shirt, Mum could deduce who had eaten the last cookie.",
"destitute-1": "The flood left the farmers destitute, with no food, no house, and no clothes.",
"diligence-1": "With quiet diligence, Wesley practised piano every single morning before school for a whole year.",
"disastrous-1": "Our first game was disastrous; we lost twelve to nothing and our goalie broke his wrist.",
"discrepancy-1": "The teacher spotted a discrepancy between my answer and the one in the marking book.",
"embroil-1": "Please don't embroil me in your argument about whose turn it is to walk the dog.",
"enamour-1": "My sister was so enamoured of the fluffy puppy that she refused to leave the shelter.",
"exquisite-1": "Grandma's exquisite lace tablecloth had tiny flowers stitched so perfectly that everyone leaned in to look.",
"fabricate-1": "Rather than admit he forgot his homework, Tom fabricated a wild story about a hungry dog.",
"frugal-1": "My frugal grandma saves every coin, cuts coupons, and never wastes a single slice of bread.",
"gluttonous-1": "Our gluttonous puppy ate his whole dinner, then tried to eat the cat's food too.",
"insomnia-1": "Excited about the field trip, I had insomnia and stared at the ceiling until morning.",
"intangible-1": "Friendship is intangible, since you cannot hold it, weigh it, or put it in a box.",
"reproach-1": "Mom said nothing, but the reproach in her eyes told me she saw the mess.",
"scarcity-1": "Because of the scarcity of rain this summer, our garden turned brown and crispy.",
"scrutinise-1": "The judges scrutinise every science project, checking the charts and asking careful questions about our results.",
"seldom-1": "Our cat seldom comes inside, so we were shocked to find her sleeping on my bed.",
"simultaneous-1": "Our simultaneous shouts of \"Goal!\" made the whole crowd laugh, because we yelled the exact same moment.",
"skirmish-1": "A brief skirmish broke out over the last soccer ball, but our teacher settled it quickly.",
"solitary-1": "A solitary penguin stood on the ice while the rest of the group swam away.",
"stagnate-1": "If you never read harder books, your reading skills will stagnate and stop getting better.",
"stupendous-1": "Her stupendous catch in the last second made the whole crowd jump up and cheer.",
"suave-1": "In his neat suit and polished shoes, my uncle looked suave enough to host a show.",
"succinct-1": "Instead of a long story, give me a succinct answer: who broke the window?",
"swindled-1": "The man at the fair swindled Dad, selling him a bike with no brakes.",
"versatile-1": "My versatile teammate can play goalie, defense, or forward whenever the coach needs him.",
"vicinity-1": "Mom told us to stay in the vicinity of the tent, never far into the woods.",
"wholesome-1": "Camp felt wholesome: fresh air, real food, kind friends, and no screens for a week.",
"wretched-1": "The wretched stray dog shivered in the rain with muddy fur and no home."
};
